package streams

import "fmt"

// Store option type.
type Option func(store *Store) error

// Provide a system time instance, to override how timestamps are calculated.
//
// This is useful for custom timestamp calculation and for mocking.
func WithSystemTime(systemTime SystemTime) Option {
	return func(store *Store) error {
		store.systemTime = systemTime
		return nil
	}
}

// Set the id generator used to create new ids.
//
// Defaults to the [blobs.UlidIdGenerator].
//
// Notice that ids generated by the generator needs to be globally unique across
// the entire system.
func WithIdGenerator(idGenerator IdGenerator) Option {
	return func(store *Store) error {
		store.idGenerator = idGenerator
		return nil
	}
}
