package streams

// Store option type.
type StoreOption func(store *Store) error

// Provide a system time instance, to override how timestamps are calculated.
//
// This is useful for custom timestamp calculation and for mocking.
func WithSystemTime(systemTime SystemTime) StoreOption {
	return func(store *Store) error {
		store.systemTime = systemTime
		return nil
	}
}

// Set the id generator used to create new ids.
//
// Defaults to the [blobs.UlidIdGenerator].
//
// Notice that ids generated by the generator needs to be globally unique across
// the entire system.
func WithIdGenerator(idGenerator IdGenerator) StoreOption {
	return func(store *Store) error {
		store.idGenerator = idGenerator
		return nil
	}
}

func ApplyStoreOptions(store *Store, opts ...StoreOption) error {
	for _, opt := range opts {
		err := opt(store)
		if err != nil {
			return err
		}
	}
	return nil
}
